### ISSUE TITLE
Unable to set socialshare-text & socialshare-media property

### ISSUE THREAD

**Issue by mharoon** [720kb/angular-socialshare#12]
Hi, 
I am unable to set these property 

1- socialshare-media
2- socialshare-text

After setting these properties when I try to publish on facebook it shows only url. No image or description have been displayed while publishing.

THanks

**Comment by 45kb** [comment]
@mharoon Hi, are you trying to share on facebook only? 
The problem is that facebook does not allow anything other than the url when sharing from the sharer url, to set up  medias , descriptions, title etc... you need to use the Open Graph meta tags

Reference: https://github.com/720kb/angular-socialshare/issues/6

**Comment by mharoon** [comment]
Hi, Yea you are right I am trying to share it on facebook only. 

Thanks for the quick response and reference.

**Comment by 45kb** [comment]
@mharoon  you're welcome at anytime, have a nice day :+1:

**Comment by yasirrafiq33** [comment]
Hi,
Can you just show steps how we can add these things on facebook using graph tags.
