### ISSUE TITLE
Custom via URL Support (at least for Twitter)

### ISSUE THREAD

**Issue by ishansharma** [720kb/angular-socialshare#152]
'via' accepts only handles for Twitter right now. So tweet goes like this: 

> Angular Socialshare on Github https://github.com/720kb/angular-socialshare/ via @720kb

I want to replace handle with a URL. So it should become: 

> Angular Socialshare on Github https://github.com/720kb/angular-socialshare/ via http://720kb.net/

Right now, I could not find a way to do it easily. So I plan on adding another attribute, socialshare-viatext where you can give plaintext. 

I was wondering if this is something you guys would be fine having in here or if I should create a fork and use that. 

Thank you.

**Comment by 45kb** [comment]
Hi @ishansharma actually: the attribute is not needed, just because twitter `via` is clearly defined on twitter dev documentation:

> A Twitter username to associate with the Tweet, such as your site’s Twitter account. The provided username will be appended to the end of the Tweet with the text “via @username”.

Example Value: twitterdev

If you don't use a twitter username that will be the same of sharing plain text which can be done just using `socialshare-text="something via http://some.url"`

Thanks anyway and keep it up, ideas are always appreciated!

**Comment by ishansharma** [comment]
Thanks. I totally forgot that I can't add after URL and hashtags. My bad. :)

**Comment by 45kb** [comment]
No problems 👍 
Have a nice time.
