### ISSUE TITLE
After clicking Email button blank tab opens

### ISSUE THREAD

**Issue by YanivPlaybuzz** [720kb/angular-socialshare#163]
click Email button on IOS < 10.02
Result:
Blank page opened

**Comment by 45kb** [comment]
Hi please provide a code example or a jsfiddle

**Comment by bbsdwr** [comment]
in the block "manageEmailShare", there is the call $window.open(urlString, '_blank');
this is causing the issue, because it opens the mailto-url in a new tab (which then is blank, because it is only a mailto-url and not a webpage-call)

when the target in the call is replaced with '_self' instead, it does work without opening blank tabs/pages

this misbehavior was added here: https://github.com/720kb/angular-socialshare/commit/3fe9f213ea856d0df82000ef117b94e9bf147452#diff-e8acc63b1e238f3255c900eed37254b8

so by reading the changes, it seems, that '_blank' is needed inside iframes, but outside of iframes, it should be '_self' to behave correctly

**Comment by levipadre** [comment]
Yes, _self would be help. I have the same problem.
Thanks

**Comment by levipadre** [comment]
Thanks!

**Comment by 45kb** [comment]
Hi, you should be ok now, @areverberi fixed it just install the new version and let know guys! thanks https://github.com/720kb/angular-socialshare/releases/tag/2.3.2
