### ISSUE TITLE
Close facebook dialog after posting

### ISSUE THREAD

**Issue by levivm** [720kb/angular-socialshare#49]
Is there any way to close facebook dialog after sharing a link ? 

I tried to set `redirect_uri` to "myurl.com/close-window" and inside that state tried to perform `$window.close()`, but scripts may close a window that were opened by it. 

May be there is a way to set a callback function to `$window.open` and close it after a post happen.

**Comment by 45kb** [comment]
hi @levivm  looks like is not possible to add callbacks without using providers own SDK (API), this module at the moment doesn't implement SDKs since is designed to work without them.

If you find any good solution without having to include the SDK let know please.

We already talked about callbacks you can refer https://github.com/720kb/angular-socialshare/issues/36

Thank you.

**Comment by 45kb** [comment]
found this in case you want to give it a try http://stackoverflow.com/questions/15180676/how-do-i-close-the-popup-after-i-post-to-facebook

**Comment by levivm** [comment]
Thx, but I already tried that, the problem is that chrome does not allow to close a window that has been opened by other script.
