### ISSUE TITLE
Share programmatically 

### ISSUE THREAD

**Issue by softBarbarian** [720kb/angular-socialshare#74]
Is there a way to share content programmatically not by using directives? We need to use external network call to create share content and have a need to share that dynamically created content.
Thanks

**Comment by 45kb** [comment]
Hi @softBarbarian  the only way it comes to my mind for the moent is to use https://github.com/720kb/angular-socialshare#sharing-event-trigger

So that, as you retrieve your content, you could trigger the event on the element and it opens the popup.

The element could be hidden or visible as you wish.

**Comment by softBarbarian** [comment]
@45kb thanks for prompt reply! Can i bind a custom event ? could you please provide an example? thanks

**Comment by 45kb** [comment]
@softBarbarian we will study something to provide a better approach asap.

In the meantime custom events probably are not supported, because the trigger bind this ` element.bind(attrs.socialshareTrigger, onEventTriggered);`

So i am afraid, at the moment, you would need to trigger click or mouseover or anyother event an element can fire.

A simple and not tested example could be:

html
```
<a id="hiddenShare" ng-controller="myCtrl as ctrl" style="display:none" socialshare socialshare-text="{{ctrl.dynamicContent}}" socialshare-trigger="focus" socialshare-provider="twitter">
i am hidden but i will share
</a>
```

```javascript
.controller('myCtrl', function ($scope, $http) {
var that = this
  , elem = document.getElementById('hiddenShare');

 $http(...retrieve your data from url).then(function (data) {
 that.dynamicContent = data;
 elem.focus();
});
});
```

**Comment by softBarbarian** [comment]
@45kb thanks for your help your example works good. Just needed to use `angular.element().triggerHandler()` to get it to work. Thanks again
