### ISSUE TITLE
Window open reusing same window

### ISSUE THREAD

**Issue by hthief** [720kb/angular-socialshare#98]
Opening a facebook popup and then twitter's, will open two different windows, but opening twitter's first and then facebook's will reuse the same window. Haven't looked to hard in this, because it's a minor issue, but is something causing the window to have the same name perhaps?

**Comment by mebibou** [comment]
Maybe I'm wrong but since the popup from facebook asks you for a confirmation when you try to close it, I would guess this is the reason why you can do it one way but not the other. If you try doing the same with Skype for example, you will have the same result, i.e. facebook one always the one not wanted to be replaced. You should talk to those guys ;)

**Comment by 45kb** [comment]
this should be closed now, popup titles should do the fix now.

If not please just let know here.

thanks
